### ISSUE TITLE
Prevent webpack from bundling the code

### ISSUE THREAD

**Issue by Eddie-CooRo** [Eddie-CooRo/express-hooks#50]
Webpack bundles our code by default, but it's not our expected behaviour, because in nodejs, we have cjs built-in.
So I wonder if we can make webpack to leave reqire statements as is and only convert esmodule imports/exports to their esmodule equivalents.
If we have to migrate completely to commonjs in order to achieve this, it's not a problem

**Comment by eddiecooro** [comment]
Fixed in v0.2.2
